<?php

declare(strict_types=1);

namespace SohoPHP\SoFinder\DependencyInjection;

use Symfony\Component\Config\Definition\Builder\TreeBuilder;
use Symfony\Component\Config\Definition\ConfigurationInterface;

final class Configuration implements ConfigurationInterface
{
    public function getConfigTreeBuilder(): TreeBuilder
    {
        $tree = new TreeBuilder('so_finder');
        $tree->getRootNode()
            ->children()
                ->scalarNode('route_prefix')->defaultValue('/admin/sofinder')->end()
                ->scalarNode('cache_dir')->defaultValue('%kernel.cache_dir%/sofinder')->end()
                ->scalarNode('metadata_file')->defaultValue('%kernel.project_dir%/var/sofinder/metadata.json')->end()
                ->scalarNode('quarantine_dir')->defaultValue('%kernel.cache_dir%/sofinder/quarantine')->end()
                ->scalarNode('chunk_dir')->defaultValue('%kernel.cache_dir%/sofinder/chunks')->end()
                ->scalarNode('usage_dir')->defaultValue('%kernel.project_dir%/var/sofinder/usage')->end()
                ->integerNode('chunk_size')->min(262144)->max(16777216)->defaultValue(5242880)->end()
                ->integerNode('max_upload_chunks')->min(1)->max(1000)->defaultValue(200)->end()
                ->scalarNode('trash_dir')->defaultValue('%kernel.project_dir%/var/sofinder/trash')->end()
                ->integerNode('trash_retention_days')->min(1)->max(3650)->defaultValue(30)->end()
                ->integerNode('trash_max_items')->min(1)->max(100000)->defaultValue(1000)->end()
                ->integerNode('trash_max_bytes')->min(1)->defaultValue(1073741824)->end()
                ->arrayNode('image_processing')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->enumNode('driver')->values(['auto', 'gd', 'imagick'])->defaultValue('auto')->end()
                        ->integerNode('max_width')->min(1)->max(100000)->defaultValue(12000)->end()
                        ->integerNode('max_height')->min(1)->max(100000)->defaultValue(12000)->end()
                        ->integerNode('max_single_frame_pixels')->min(1)->defaultValue(50000000)->end()
                        ->integerNode('max_frames')->min(1)->max(10000)->defaultValue(200)->end()
                        ->integerNode('max_total_pixels')->min(1)->defaultValue(100000000)->end()
                        ->integerNode('memory_bytes')->min(16777216)->defaultValue(268435456)->end()
                        ->integerNode('map_bytes')->min(16777216)->defaultValue(536870912)->end()
                        ->integerNode('disk_bytes')->min(16777216)->defaultValue(1073741824)->end()
                        ->integerNode('threads')->min(1)->max(16)->defaultValue(1)->end()
                        ->integerNode('timeout_seconds')->min(1)->max(300)->defaultValue(30)->end()
                    ->end()
                ->end()
                ->arrayNode('ui')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('folder_tree')->defaultFalse()->end()
                        ->enumNode('scale')->values(['compact', 'standard', 'large', 'xlarge'])->defaultValue('standard')->end()
                    ->end()
                ->end()
                ->arrayNode('maintenance')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->enumNode('mode')->values(['inline', 'messenger', 'external', 'disabled'])->defaultValue('inline')->end()
                        ->integerNode('min_interval_seconds')->min(0)->max(86400)->defaultValue(300)->end()
                        ->integerNode('max_items_per_run')->min(1)->max(10000)->defaultValue(50)->end()
                    ->end()
                ->end()
                ->arrayNode('limits')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->arrayNode('normal')->addDefaultsIfNotSet()->children()->integerNode('max_requests')->min(0)->defaultValue(240)->end()->integerNode('interval')->min(1)->defaultValue(60)->end()->integerNode('max_concurrent')->min(0)->defaultValue(12)->end()->end()->end()
                        ->arrayNode('upload')->addDefaultsIfNotSet()->children()->integerNode('max_requests')->min(0)->defaultValue(30)->end()->integerNode('interval')->min(1)->defaultValue(60)->end()->integerNode('max_concurrent')->min(0)->defaultValue(3)->end()->end()->end()
                        ->arrayNode('image')->addDefaultsIfNotSet()->children()->integerNode('max_requests')->min(0)->defaultValue(60)->end()->integerNode('interval')->min(1)->defaultValue(60)->end()->integerNode('max_concurrent')->min(0)->defaultValue(2)->end()->end()->end()
                        ->arrayNode('thumbnail')->addDefaultsIfNotSet()->children()->integerNode('max_requests')->min(0)->defaultValue(600)->end()->integerNode('interval')->min(1)->defaultValue(60)->end()->integerNode('max_concurrent')->min(0)->defaultValue(16)->end()->end()->end()
                        ->arrayNode('archive')->addDefaultsIfNotSet()->children()->integerNode('max_requests')->min(0)->defaultValue(10)->end()->integerNode('interval')->min(1)->defaultValue(60)->end()->integerNode('max_concurrent')->min(0)->defaultValue(1)->end()->end()->end()
                        ->arrayNode('transfer')->addDefaultsIfNotSet()->children()->integerNode('max_requests')->min(0)->defaultValue(60)->end()->integerNode('interval')->min(1)->defaultValue(60)->end()->integerNode('max_concurrent')->min(0)->defaultValue(2)->end()->end()->end()
                    ->end()
                ->end()
                ->arrayNode('image_presets')
                    ->useAttributeAsKey('name')
                    ->arrayPrototype()
                        ->children()
                            ->integerNode('width')->min(1)->max(4096)->isRequired()->end()
                            ->integerNode('height')->min(1)->max(4096)->isRequired()->end()
                            ->integerNode('quality')->min(1)->max(100)->defaultValue(88)->end()
                        ->end()
                    ->end()
                    ->defaultValue([])
                ->end()
                ->arrayNode('theme')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->scalarNode('accent')->defaultValue('#276ef1')->end()
                        ->scalarNode('background')->defaultValue('#f4f6f9')->end()
                        ->scalarNode('panel')->defaultValue('#ffffff')->end()
                        ->scalarNode('text')->defaultValue('#1c2735')->end()
                        ->scalarNode('muted')->defaultValue('#667282')->end()
                        ->scalarNode('danger')->defaultValue('#c13a43')->end()
                        ->scalarNode('radius')->defaultValue('10px')->end()
                    ->end()
                ->end()
                ->arrayNode('resources')
                    ->isRequired()
                    ->requiresAtLeastOneElement()
                    ->useAttributeAsKey('name')
                    ->arrayPrototype()
                        ->children()
                            ->scalarNode('adapter')->defaultValue('local')->cannotBeEmpty()->end()
                            ->variableNode('options')->defaultValue([])->end()
                            ->scalarNode('root')->isRequired()->cannotBeEmpty()->end()
                            ->scalarNode('public_url')->defaultValue('')->end()
                            ->enumNode('delivery_mode')->values(['public', 'proxy'])->defaultValue('public')->end()
                            ->arrayNode('allowed_extensions')->scalarPrototype()->end()->defaultValue([])->end()
                            ->arrayNode('denied_extensions')->scalarPrototype()->end()->defaultValue(['php', 'phtml', 'phar', 'cgi', 'pl', 'exe', 'sh', 'html', 'htm', 'js'])->end()
                            ->arrayNode('allowed_mime_types')->scalarPrototype()->end()->defaultValue([])->end()
                            ->integerNode('max_size')->min(1)->defaultValue(20971520)->end()
                            ->booleanNode('read_only')->defaultFalse()->end()
                            ->integerNode('quota')->min(0)->defaultValue(0)->end()
                            ->integerNode('max_file_name_length')->min(1)->max(255)->defaultValue(120)->end()
                            ->integerNode('max_folder_name_length')->min(1)->max(255)->defaultValue(50)->end()
                            ->integerNode('max_folder_depth')->min(1)->max(100)->defaultValue(5)->end()
                            ->integerNode('max_image_pixels')->min(1)->defaultValue(50000000)->end()
                            ->integerNode('max_batch_items')->min(1)->max(1000)->defaultValue(100)->end()
                            ->integerNode('max_recursive_items')->min(1)->max(100000)->defaultValue(10000)->end()
                            ->integerNode('max_archive_items')->min(1)->max(100000)->defaultValue(1000)->end()
                            ->integerNode('max_archive_bytes')->min(1)->defaultValue(536870912)->end()
                            ->integerNode('max_image_width')->min(1)->max(100000)->defaultValue(12000)->end()
                            ->integerNode('max_image_height')->min(1)->max(100000)->defaultValue(12000)->end()
                            ->enumNode('animated_image_policy')->values(['preserve', 'reject'])->defaultValue('preserve')->end()
                            ->arrayNode('roles')->scalarPrototype()->end()->defaultValue([])->end()
                            ->arrayNode('operation_roles')
                                ->useAttributeAsKey('operation')
                                ->arrayPrototype()->scalarPrototype()->end()->end()
                                ->defaultValue([])
                            ->end()
                            ->arrayNode('path_acl')
                                ->arrayPrototype()
                                    ->children()
                                        ->scalarNode('path')->defaultValue('')->end()
                                        ->arrayNode('operations')->isRequired()->requiresAtLeastOneElement()->scalarPrototype()->end()->end()
                                        ->arrayNode('roles')->scalarPrototype()->end()->defaultValue([])->end()
                                        ->booleanNode('allow')->defaultTrue()->end()
                                    ->end()
                                ->end()
                                ->defaultValue([])
                            ->end()
                        ->end()
                    ->end()
                ->end()
            ->end();

        return $tree;
    }
}
