imports:
  - { resource: '../s3/so_finder.yaml' }

so_finder:
  resources:
    S3Files2:
      adapter: s3
      root: "%env(SOFINDER_PROVIDER_PREFIX2)%"
      public_url: "%env(SOFINDER_PROVIDER_PUBLIC_URL2)%"
      delivery_mode: proxy
      allowed_extensions: [txt, md, csv, tsv, rtf, pdf, doc, docx, odt, xls, xlsx, ods, ppt, pptx, odp, jpg, jpeg, png, gif, webp, svg, avif, bmp, ico, heic, heif, tif, tiff, zip, 7z, rar, tar, gz, tgz, mp3, wav, ogg, m4a, flac, mp4, webm, mov]
      roles: [ROLE_USER]
      options:
        bucket: "%env(SOFINDER_PROVIDER_BUCKET2)%"
        region: "%env(SOFINDER_PROVIDER_REGION2)%"
        endpoint: "%env(SOFINDER_PROVIDER_ENDPOINT2)%"
        use_path_style_endpoint: "%env(bool:SOFINDER_PROVIDER_USE_PATH_STYLE_ENDPOINT2)%"
        access_key_id: "%env(SOFINDER_PROVIDER_ACCESS_KEY2)%"
        secret_access_key: "%env(SOFINDER_PROVIDER_SECRET_KEY2)%"
        session_token: "%env(SOFINDER_PROVIDER_SESSION_TOKEN2)%"
